# Generated by Django 5.1.5 on 2025-05-18 10:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_chatmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Chat Log', 'verbose_name_plural': 'Chat Logs'},
        ),
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Chat Message', 'verbose_name_plural': 'Chat Messages'},
        ),
        migrations.AlterModelOptions(
            name='library',
            options={'ordering': ['title'], 'verbose_name': 'Library Book', 'verbose_name_plural': 'Library Books'},
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Archived'),
        ),
        migrations.AddField(
            model_name='library',
            name='isbn',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='chatlog',
            name='bot_response',
            field=models.TextField(verbose_name='Bot Response'),
        ),
        migrations.AlterField(
            model_name='chatlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='chatlog',
            name='user_query',
            field=models.TextField(verbose_name='User Message'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='bot_response',
            field=models.TextField(verbose_name='Bot Reply'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='user_message',
            field=models.TextField(verbose_name='User Input'),
        ),
        migrations.AlterField(
            model_name='library',
            name='author',
            field=models.CharField(max_length=100, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='library',
            name='available_copies',
            field=models.PositiveIntegerField(default=1, verbose_name='Available Copies'),
        ),
        migrations.AlterField(
            model_name='library',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='library',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='book_covers/', verbose_name='Cover Image'),
        ),
        migrations.AlterField(
            model_name='library',
            name='publication_date',
            field=models.DateField(blank=True, null=True, verbose_name='Publication Date'),
        ),
        migrations.AlterField(
            model_name='library',
            name='title',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Book Title'),
        ),
    ]
